services:
  postgres:
    image: postgres:16
    container_name: eimune-postgres
    restart: always
    environment:
      POSTGRES_USER: eimune
      POSTGRES_PASSWORD: eimune123
      POSTGRES_DB: eimune_db
    ports:
      - "6032:5432"
    volumes:
      - eimune_pgdata:/var/lib/postgresql/data
volumes:
  eimune_pgdata: